// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tumin.Cargo.DataAccessLayer.Concrete;

#nullable disable

namespace Tumin.Cargo.DataAccessLayer.Migrations
{
    [DbContext(typeof(CargoDbContext))]
    partial class CargoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tumin.Cargo.EntityLayer.Concrete.CargoCompany", b =>
                {
                    b.Property<int>("CargoCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CargoCompanyId"));

                    b.Property<string>("CargoCompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CargoCompanyId");

                    b.ToTable("CargoCompanies");
                });

            modelBuilder.Entity("Tumin.Cargo.EntityLayer.Concrete.CargoCustomer", b =>
                {
                    b.Property<int>("CargoCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CargoCustomerId"));

                    b.Property<string>("CargoCustomerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoCustomerCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoCustomerCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoCustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoCustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoCustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoCustomerSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CargoCustomerId");

                    b.ToTable("CargoCustomers");
                });

            modelBuilder.Entity("Tumin.Cargo.EntityLayer.Concrete.CargoDetail", b =>
                {
                    b.Property<int>("CargoDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CargoDetailId"));

                    b.Property<int>("CargoCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("CargoTrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiverCustomer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderCustomer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CargoDetailId");

                    b.HasIndex("CargoCompanyId");

                    b.ToTable("CargoDetails");
                });

            modelBuilder.Entity("Tumin.Cargo.EntityLayer.Concrete.CargoOperation", b =>
                {
                    b.Property<int>("CargoOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CargoOperationId"));

                    b.Property<DateTime>("CargoOperationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CargoOperationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CargoTrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CargoOperationId");

                    b.ToTable("CargoOperations");
                });

            modelBuilder.Entity("Tumin.Cargo.EntityLayer.Concrete.CargoDetail", b =>
                {
                    b.HasOne("Tumin.Cargo.EntityLayer.Concrete.CargoCompany", "CargoCompany")
                        .WithMany()
                        .HasForeignKey("CargoCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoCompany");
                });
#pragma warning restore 612, 618
        }
    }
}
